name: CI (CUDA, ubuntu)

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
    paths: [
      '.github/workflows/build-cuda-ubuntu.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp',
      '**/*.cu',
      '**/*.cuh'
    ]

  pull_request:
    types: [opened, synchronize, reopened]
    paths: [
      '.github/workflows/build-cuda-ubuntu.yml',
      'ggml/src/ggml-cuda/**'
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  cuda:
    runs-on: ubuntu-24.04
    container: nvidia/cuda:12.6.2-devel-ubuntu24.04

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Mark Git directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y cmake build-essential gcc-13 g++-13 ninja-build libgomp1 git libssl-dev pkg-config libcurl4-openssl-dev

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.21
        with:
          key: cuda-ubuntu-24.04-cuda
          evict-old-files: 1d
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Build with CMake
        run: |
          cmake -S . -B build-v2 \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=gcc-13 \
            -DCMAKE_CXX_COMPILER=g++-13 \
            -DCMAKE_CUDA_HOST_COMPILER=g++-13 \
            -DCMAKE_CUDA_ARCHITECTURES="70;75;80;86;89;90" \
            -DGGML_CUDA=ON \
            -DGGML_CUDA_FA_ALL_QUANTS=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CUDA_COMPILER_LAUNCHER=ccache
          cmake --build build-v2 --target llama-server -j 2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llama-server-cuda
          path: build-v2/bin/llama-server
